# Generated by Django 5.1.7 on 2025-03-21 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='検索クエリ')),
                ('result', models.TextField(verbose_name='検索結果')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='検索日時')),
                ('model', models.CharField(max_length=50, verbose_name='使用モデル')),
                ('tokens_prompt', models.IntegerField(blank=True, null=True, verbose_name='プロンプトトークン')),
                ('tokens_completion', models.IntegerField(blank=True, null=True, verbose_name='完了トークン')),
                ('tokens_total', models.IntegerField(blank=True, null=True, verbose_name='合計トークン')),
            ],
            options={
                'verbose_name': '検索履歴',
                'verbose_name_plural': '検索履歴',
                'ordering': ['-timestamp'],
            },
        ),
    ]
